version: '3.4'
volumes:
  {maven-repos}
services:
  maven:
    image: maven:3.8.4-openjdk-17
    expose:
      - 8080
    volumes:
      - .:/usr/maven/project
      - maven-repos:/root/.m2
    working_dir: /usr/maven/project
    entrypoint: mvn clean spring-boot:run
    ports:
      - "8080:8080"
    environment:
      ACCESS_KEY: 'VjR8vu5p3QY5cvwP'